all: exercise1b exercise1d exercise2 exercise3


exercise1b: exercise1b.c
	gcc -Wall -Wextra exercise1b.c -o exercise1b

exercise1d: exercise1d.c
	gcc -Wall -Wextra exercise1d.c -o exercise1d

exercise2: exercise2.c
	gcc -O3 -Wall -Wextra  exercise2.c -o exercise2

exercise3:exercise3.c
	gcc -std=c99 -Wall -Wextra exercise3.c -o exercise3
