exercise1: exercise1.c magic_function.o
	gcc -g -fno-stack-protector -std=c99 -o exercise1 exercise1.c magic_function.o

magic_function.o: magic_function.c
	gcc -g -c -fno-stack-protector -std=c99 -o magic_function.o magic_function.c
